import {
    REG_PENDING,
    REG_SUCCESS,
    REG_FAILED,
    LOGIN_PENDING,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    GET_ARTIST_START,
    GET_ARTIST_SUCCESS,
    GET_ARTIST_FAILED,
} from '../actions/index';

